### ISSUE TITLE
Connect to only one device

### ISSUE THREAD

**Issue by palatinb** [Apollon77/meross-cloud#129]
Hello,

Could you please show an example how to connect to only one selected (with uuid) device. 

Thank you.

**Comment by Apollon77** [comment]
The newest version now on GitHub (soon npm) is only initializing one MQTT connection to Meros cloud for alle device communications and also supports local communication. Single device objects can use "connect" to tell that they want to get updates ... else they would not get infos. maybe that helps already for your use case? Please check it out
