### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tkbstudios** [Apollon77/meross-cloud#165]
**Describe the bug**  

**To Reproduce**  
1. Setup the files
2. enter e-mail and password
3. run using 'node .'
4. No error and console just closes without output

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: Latest version of 02-14-2023
 - JS-Controller version: Latest version of 02-14-2023
 - Node version: v18.12.1
 - Operating system: Windows 11

**Additional context**  
Can't find where to get the secret key.

**Comment by Apollon77** [comment]
>  Can't find where to get the secret key.

What secret key you mean? you need to use your Meross username and password

**Comment by tkbstudios** [comment]
The secret key in the index.js file

**Comment by Apollon77** [comment]
What dio you mean? You change nothing on index.js ... you just use the Library ... see example

**Comment by tkbstudios** [comment]
What is that then?

![image](https://user-images.githubusercontent.com/69647028/218797294-7085e0f3-5a28-4173-aeb9-1ca3ddb560eb.png)

**Comment by tkbstudios** [comment]
Ok but still doesn't work..

**Comment by tkbstudios** [comment]
Ok but still doesn't work..

**Comment by Apollon77** [comment]
Honestly ... Doesn't work is no error description that can be used by anyone. The library works because several thousand users in ioBorke rand also other ases use it successfully.

So please post:
1.) What exactly you do, post your code
2.) What errors you get? Please set console.log as logger to the library and post the log output
