### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by 404invalid-user** [Apollon77/meross-cloud#166]
**Is your feature request related to a problem? Please describe.**

i have no clue how to use anything and what exists other than the toggle in the example

**Describe the solution you'd like**

documentation / more example code 

**Describe alternatives you've considered**

reverse engineering this library but i have little to no understanding of things like payloads that you would send to their api

**Additional context**

**Comment by Apollon77** [comment]
I agree that it could be much better documented, but I do not have time for this right now. In fact you initialize the connection and will get one object per device. Then you ned to check the device meta data to know which kind of device it is and check the cpabilities to understand which functions the device have and then you can use the respective methods to control devices.

There is an iobroker adapter that implements all this ... I can only point you there right now. https://github.com/Apollon77/ioBroker.meross/blob/master/main.js . Sorry

**Comment by 404invalid-user** [comment]
ah ok thank you for the reply
