### ISSUE TITLE
QUESTION: How does MFA work if you need a new code for every login

### ISSUE THREAD

**Issue by Darrilla** [Apollon77/meross-cloud#181]
The way this library works, you create a MerossCloud object with options, and then call connect. The problem I have if I turn on MFA is that I don't understand how to get that MFA code without user interaction. What is the expected way to handle this?

**Comment by Apollon77** [comment]
it is simply not possible ... thats why the newest version has a "getTokenData" method which can be called after a connection and allows to pas these data into the constructor options.
So when MFA ois active the token can be reused as long as the token is valid ... Currently no token refreshs are possible.

**Comment by Darrilla** [comment]
> it is simply not possible ... thats why the newest version has a "getTokenData" method which can be called after a connection and allows to pas these data into the constructor options. So when MFA ois active the token can be reused as long as the token is valid ... Currently no token refreshs are possible.

Any idea of the expiration for these tokens?

**Comment by Apollon77** [comment]
I assume we will find out :-) So, nope
