### ISSUE TITLE
MSS315 -  Can not get Data for Device : undefined

### ISSUE THREAD

**Issue by Herbert-Testmann** [Apollon77/meross-cloud#183]
MSS315
FW 9.5.35

unknown device type.
What data can I provide to enter the device type?

**Comment by Apollon77** [comment]
Please start the adapter with Debug loglevel and post the full log from /opt/iobroekr/logs/... from that start

**Comment by Herbert-Testmann** [comment]
I have the log file.
Is there any credentials in the log that I should delete before publishing?

**Comment by Herbert-Testmann** [comment]
new test results
- my phone with the app is not in local WiFi
I can control the actuator via the meross app and see the power currently used.

- ioBroker shows the device as "offline"
- the status of the switch (channel 0) still changes

- the current is not displayed
- the power is not displayed
- voltage is an old value

![image](https://github.com/Apollon77/meross-cloud/assets/20645041/5d7f9cf5-e62a-47ff-871d-81a074095503)

**Comment by Apollon77** [comment]
because this is a common ndevice that works ... try to restart the device ... (power off and connect again) ... how many devices you have in your meross account?

**Comment by Herbert-Testmann** [comment]
a restart does not solve the problem.

I have 7 devices

4 WiFi switchable sockets with current measurement
2 WiFi lamps
1 matter switchable sockets with current measurement

The matter socket is the problem

![image](https://github.com/Apollon77/meross-cloud/assets/20645041/5562e65a-3da8-4254-8600-ae9253ece3ff)

**Comment by Apollon77** [comment]
Then I need the debug log please ... but to me it more looks like that this device has local communication issues ... does it work if you set in the states to NOT connect locally but via cloud?

**Comment by Herbert-Testmann** [comment]
_does it work if you set in the states to NOT connect locally but via cloud?_

yes , it work. 
all data has the current status

one of the MSS310 had the same problem today. After switching to cloud only, this also works immediately.
Do we want to close the topic first and I'll watch it?
Or can you change something on the software side in the case of local communication?

**Comment by Herbert-Testmann** [comment]
I have now seen that the actuator is not connected to the WiFi in the event of an error. This is what the log file in the router shows me.
I will first try to solve this local problem.
The devices can only communicate over 2.4GHz. When setting up you have to switch off the 5GHz in the Fritz Box.
In some articles on the Internet you can read that there are problems with these devices with the Fritz Box.
So I'll first try everything to improve the local network.
