### ISSUE TITLE
MSL120DA - Can not get Data for Device: undefined

### ISSUE THREAD

**Issue by Herbert-Testmann** [Apollon77/meross-cloud#184]
unknown device type.
What data can I provide to enter the device type?

MSL120DA
lamp
FW 7.2.7

**Comment by Apollon77** [comment]
Please start the adapter with Debug loglevel and post the full log from /opt/iobroekr/logs/... from that start

**Comment by Herbert-Testmann** [comment]
It was a local problem. The lamps are now recognized.
