### ISSUE TITLE
Auth failure since 11/02/2024

### ISSUE THREAD

**Issue by romaint2b** [Apollon77/meross-cloud#188]
Hi,
I use your plugin since few month and everything works perfectly except since monday (thank you ;) ). 
On Monday 11 february it seems that the auth service of meross IOT doesn't sent response.

I activate a console.log in meross-cloud/index.js and i have this message : "undefined" when i want to display  the variable.
After that i have a message that say : No valid Login Response data received.

Here is the code wich fail :
```
this.authenticatedPost(LOGIN_URL, data, (err, loginResponse) => {
            console.log(loginResponse);
            if (err) {
                callback && callback(err);
                return;
            }
            if (!loginResponse) {
                callback && callback(new Error('No valid Login Response data received'));
                return;
            }
```

And here are the logs :
0|meross2d | 2024-02-15T20:53:45.361Z -- Dummy hardware found (12). Autocreate enabled
0|meross2d | undefined
0|meross2d | 2024-02-15T20:53:45.458Z -- connect error: Error: No valid Login Response data received

Do you have an idea of what is happening ?

**Comment by romaint2b** [comment]
Ok, i Use an old version probably due to meross2domoticz plugin dependecy. I replace the index by the current index.js and it works :).

**Comment by romaint2b** [comment]
Closing issue.

**Comment by romaint2b** [comment]
-

**Comment by Apollon77** [comment]
Cool it works, maybe please tell the other project to upgrade the dependency officially
