### ISSUE TITLE
Issue w async_forward_entry_setup

### ISSUE THREAD

**Issue by paquitoloco** [Apollon77/meross-cloud#194]
**Describe the bug**  

When launching HA in docker container, in the logs of the container I get the following error:

"Detected code that calls async_forward_entry_setup for integration meross_cloud with title: https://iotx-eu.meross.com and entry_id: 01JFASG9RXXR4WVQTX7CQ3AYBT, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue"

This means that from the next release of HA, meross cloud could not work.

Can you confirm?

Many thanks for your help.

**Comment by Apollon77** [comment]
Hm ... I think your should open this issue in the home assistant addon or library ... it is not this one as I know
