### ISSUE TITLE
Help Impliment into Homebridge plugin

### ISSUE THREAD

**Issue by donavanbecker** [Apollon77/meross-cloud#33]
Anyway you could help me implement this project into my homebridge plugin? So that meross devices can be recognized by homebridge?

https://github.com/donavanbecker/homebridge-meross

**Comment by Apollon77** [comment]
What kind of help do you need?

In fact at https://github.com/Apollon77/ioBroker.meross/blob/master/main.js you find the ioBroker adapter which also uses this library. The library only helps you to generally get information and controll stuff ... all the "semantics" (so differentiate device types and there fields in reading and to control) you need to implement ... see https://github.com/Apollon77/ioBroker.meross/blob/master/main.js#L196 ... so you need to see what field from device maps how to homebridge ... Sorry but I can not really help with that part of the story, but I'm willing to support on questions or to help you understand the code I did there  ...

**Comment by donavanbecker** [comment]
Okay! Thanks for sharing I will look into that! That helps
