### ISSUE TITLE
MSL120 - Unable to change RGB color

### ISSUE THREAD

**Issue by Fabiomad85** [Apollon77/meross-cloud#4]
Hi!

thank for your amazing job with this project.

I have a MSL120, I'm able to toggle my bulb, dimmer it, but I cant change the rgb color.

let payload1 = {
                "light":{
                    "capacity":6,
                    "channel":0,
                    "rgb":289,
                    "temperature":80,
                    "luminance":100
                }
            };
            device.publishMessage('SET', 'Appliance.Control.Light', payload1, (err, res)=>{
                console.log(err);
                console.log('PublishMessage response'+JSON.stringify(res));
            });

Response is 
 Appliance.Control.Light - data: {"light":{"capacity":6,"channel":0,"rgb":127,"temperature":80,"luminance":100}}

What Do I am wrong?

Thank you
Fab

**Comment by Apollon77** [comment]
Please start adapter with debug log and provide full log from the start, then I can add support for it. Thank you

**Comment by Apollon77** [comment]
Please ignore my last message.
Please provide a logger in the options and provide a log of the whole initialization including calls to getSystemAbilities and getSystemAllData

Is the rgb color really encoded into number?

So additionally have it connected and then change the colors via the meross app and note down colors and receied "Appliance.Control.Light" notifies and provide here.

I never had such a lamp, so I need to see what happens to maybe adopt something :-)

**Comment by Apollon77** [comment]
The light value here seems more meaningful, so it seems they convert the RGB value in an number representation ... Depending on how they encode the color 4063487 can be #3E00FF (more or less blue) or #FF003F (more or less red). What was set in this case?

And for your initial example where you provided 289 and the device returned 127 it is good possible that the device in reality can just do "some" colors and so it is normal that the real set value is changed a bit depending on what you set. This color btw matches to kind of a black in both cases :-)

**Comment by Apollon77** [comment]
@Fabiomad85 did you found out about the color integer if it is RRGGBB or BBGGRR coded?

**Comment by Apollon77** [comment]
method is included in lib 1.1.0

**Comment by polgiron** [comment]
hey @Apollon77 could you please explain how to encode the color number from an RGB value?

**Comment by Apollon77** [comment]
it should be something like: construct a 6 char hex string with rrggbb and convert that into a number like parteInt("rrggbb", 16);

**Comment by polgiron** [comment]
Amazing it does work, thank you.

```
const hex = '1a20e8';
const color = parseInt(hex, 16);
```

**Comment by Apollon77** [comment]
Only thing is that it might be "rrggbb" or "bbggrr" :-)
