### ISSUE TITLE
ControlToggleX callback functionality is broken

### ISSUE THREAD

**Issue by filiptc** [Apollon77/meross-cloud#58]
Hi there, thanks for building this library! The messageId reference seems to mismatch the one from the response of toggleX operations, so the mapping fails and a "Timeout" Error is thrown into the callback after 20s.

Looking at the code comments in the code, I'm assuming you're aware of this. I'm not familiar with MQTT, so I'm not sure how to map requests to the response in order to trigger the specific callback, but let me know if you need more info or if I can help in any other way with this.

Cheers

**Comment by Apollon77** [comment]
Which code comments you mean? Normally this works good and I‘m not really aware of problems with the callback. Normally such cases mean that the request data are invalid when I remember correctly. 

Can you show code or such please where it happens?

**Comment by filiptc** [comment]
Interesting that you think it might be a bad request, since I am successfully toggling the state of my Meross device. I used node breakpoints to debug and saw that the [messageId stored](https://github.com/Apollon77/meross-cloud/blob/master/index.js#L328) does not match the [messageId of the server response](https://github.com/Apollon77/meross-cloud/blob/master/index.js#L276) (i.e. the server does respond successfully). Hence, callback is not triggered and the timeout kicks in. My call was:
```js
  const merossCloud = new MerossCloud(config);
  await new Promise(r => merossCloud.connect(r));
  const device = merossCloud.devices['myDeviceId'];
  device.controlToggleX(1, state);
```

I noticed a couple of serialized toggleX event messages [logged throughout the code](https://github.com/Apollon77/meross-cloud/blob/master/index.js#L180-L191), and assumed it might have to do with it.

Thanks for your help. Let me know if you need more info.

**Comment by Apollon77** [comment]
Then please add logging (should be enough to provide "Logger" in the settings objects so that we exactly see whats flowing ... I did not experienced such behaviour before because it would mean that meross has an error on their side ... we shpuld be able to see that in a log.

**Comment by filiptc** [comment]
Apologies for the late reply, I haven't been able to get my hands on this (pet) project during my work-week. I'm currently doing some more digging in the direction you pointed, but it looks like the configured logger only affects authentication and getDevices, not toggleX.

I'm effectively sending out requests (i.e. my plug changes state, but no toggleX request is logged). I'll keep digging the next couple of days and will write back if I find out anything. Thanks again!

**Comment by filiptc** [comment]
I've added the logger into the `publishMessage` and `this.client.on('message', (topic, message) => {` functions. This is what I'm getting (IDs masked):
```
Publishing message.
	Topic: "/appliance/[MY DEVICE ID]/subscribe".
	Message: "{
	    "header":
	    {
	        "from": null,
	        "messageId": "9e834b597d865e1bea1c35de00f3f398",
	        "method": "SET",
	        "namespace": "Appliance.Control.ToggleX",
	        "payloadVersion": 1,
	        "sign": "2cdd6b4bfe7453486622b5c5ad89da8d",
	        "timestamp": 1590223059
	    },
	    "payload":
	    {
	        "togglex":
	        {
	            "channel": 1,
	            "onoff": 1
	        }
	    }
	}".


Received message.
	Topic: "/app/[MY USER ID]/subscribe".
	Message: "{
	    "header":
	    {
	        "timestampMs": 115,
	        "timestamp": 1590223060,
	        "sign": "6adee4351134918fb9c31103c5d0d111",
	        "payloadVersion": 1,
	        "namespace": "Appliance.Control.ToggleX",
	        "method": "PUSH",
	        "messageId": "41293a99647f1f7ebe389e370f8b668a",
	        "from": "\\/appliance\\/[MY DEVICE ID]\\/publish"
	    },
	    "payload":
	    {
	        "togglex":
	        {
	            "onoff": 1,
	            "lmTime": 1590223060,
	            "channel": 1
	        }
	    }
	}".
```

As you can see, the messageIds in both the request and the response are different. I'm trying to understand why and might end up creating a pull request with a couple of changes if I find out and am able to work around it. Cheers!

**Comment by filiptc** [comment]
I found the issue: a race condition. The "connect" event on the Device had not been called yet, when I was calling the toggle event. Hence, things like MerossCloudDevice.clientResponseTopic hadn't been set yet. I'll close this ticket, as this is not a bug. Again, I might open a PR if I see any obvious improvements. Thanks again for your time!

**Comment by Apollon77** [comment]
Great info. Thank you.
