### ISSUE TITLE
MQTT connection is failing

### ISSUE THREAD

**Issue by yaydogan** [Apollon77/meross-cloud#6]
Hi,

I am seeing MQTT connection issues: 

Error: connect ECONNREFUSED 35.175.62.94:2001

I can ping "us-iot.meross.com" from my host so there is no reachability issue. Has anyone seen the same error or know what the issue might be?

Thanks in advance

**Comment by Apollon77** [comment]
you are the first one that experience this. What happens when you try

telnet 35.175.62.94 2001

??

**Comment by yaydogan** [comment]
$ nslookup us-iot.meross.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	us-iot.meross.com
Address: 34.231.175.242
Name:	us-iot.meross.com
Address: 35.175.62.94


$ telnet 34.231.175.242 2001
Trying 34.231.175.242...
telnet: Unable to connect to remote host: Connection refused

$ telnet 35.175.62.94 2001
Trying 35.175.62.94...
telnet: Unable to connect to remote host: Connection refused

**Comment by Apollon77** [comment]
Ich bekomme einen Telnet prompt.

also finde raus warum das bei Dir nicht erreicbar ist. Irgendwas im Router geblockt? Der ISP?

**Comment by Apollon77** [comment]
Geht dann die Meross App bei Dir überhaupt?
