### ISSUE TITLE
Power Usage not reporting after a while with HW version 1.0

### ISSUE THREAD

**Issue by Malaga82** [Apollon77/meross-cloud#66]
**Describe the bug**  
Hello,
i'm using a forked repo that uses your library to retrieve plugs status and power usage, [THIS](https://github.com/Malaga82/meross-hassio-addons)
Everything is working fine and i read power usage, consumption and control ON/OFF of related switch.
But i found a strabge behaviour with a plug with 1.0 hw version: after a while ( something like 5 to 10 mins ) it stops to write the related idplug_0_power, while switch status continue to work.
My MQTT topic is something like: meross/sensor/1912061548879725187848e1e912f695_0_power
And all other plugs ( i have 4 total plugs, 1 is a multiplug with 5 channels ) continue to report its states like power, consumption etc etc.
All other plugs have hw version 2.0.
Only the one with HW 1.0 stops after a while.
I have a refresh of 30 secs, tried 20 but didn't help.
Are you aware of this issue with 1.0 hw version?
Is there anything i can do or test it?
I'm not a developer by work and i'm not that skilled with node.js

**To Reproduce**  
Run the app and wait 5 to 10 mins, and watch the property like 1912061548879725187848e1e912f695_0_power stopping to write values.
I use MQTT Explorer to "track" values at each refresh, that stops with that plug.

**Expected behavior**  
meross/sensor/1912061548879725187848e1e912f695_0_power should report power values at every refresh, like other plugs do

**Screenshots & Logfiles**  
I use MQTT Explorer and after a while i see values not updated anymore, will include it when at home

**Versions:**  
 - Node version: v12.17.0 
 - Operating system: docker with alpine 3.12.0

**Additional context**  
`bash-5.0# npm list --depth=0
hassio_meross@0.1.5 /usr/src/hassio_meross

├── circular-json@0.5.9

├── meross-cloud@1.3.5

├── mqtt@4.1.0

├── mqtt-regex@1.0.5

└── q@1.5.1
`
Waiting for an answer, thanks for the library.

**Comment by Apollon77** [comment]
Hi, sorry but I can not provide support for this library that just uses mine library. I do not have the time currently to reproducethis with this library, so please deliver logs that are generated by my library ... then we can most likely see more.

**Comment by Malaga82** [comment]
Thanks for the answer, more than support my case is like a question: have you ever saw this behavior recently, with hw version 1.0 ?
I wonder if meross did some changes and affected power usage on "old" hw.
I'll try to investigate more and by side i'll build a project that use purely your library.

**Comment by Apollon77** [comment]
Honestly no idea and also did not get any report - beside that they seem to start checking and blocking devices with too many requests. Make sure not to poll energy values too often. Once every 10s is the fastest ... better 15s or more as interval.

**Comment by Malaga82** [comment]
I tested moving the plug to a new account and i can't see the error anymore.
i saw power usage stopping with merioss-iot too, so it's not likely an issue with this lib.
I'm then closing this, will report i have again this kind of issue and can debug more :)
Thanks
