### ISSUE TITLE
Detected I/O inside the event loop. 

### ISSUE THREAD

**Issue by stjones-dev** [Apollon77/meross-cloud#67]
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 6:32:50 PM (1 occurrences)
Last logged: 6:32:50 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meross_cloud doing I/O at custom_components/meross_cloud/__init__.py, line 60: http_devices = http_client.list_devices()

**Comment by Apollon77** [comment]
This lib is written in JavaScript ... not Python ... please open in correct repository
