### ISSUE TITLE
Connection to meross-cloud is continuously closing and reconnecting

### ISSUE THREAD

**Issue by bertreb** [Apollon77/meross-cloud#75]
I'm using meross-cloud in my pimatic-meross plugin. 
When I connect to meross-cloud, with 1 meross smart-plug configured, the connection is made and closed within 1-2 seconds. After the reconnect period (5 secs) the connecting and closing, starts over again. 
I reproduced this with example.js

**Comment by Apollon77** [comment]
Do you have a log please?

**Comment by bertreb** [comment]
This is a log. A mix of pimatic-debug (with timestamp) and some console.log lines I added in index.js (meross-cloud).
It's a repeating pattern every 10 seconds.

23:01:10.001 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 connected
Closing mqtt: undefined
Connect to cloud error: null
23:01:20.167 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 reconnected: undefined
Connected. Subscribe to user topics
23:01:20.312 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 connected
Closing mqtt: undefined
Connect to cloud error: null
23:01:30.004 [pimatic-meross] Handled error getSystemAbilities Error: Timeout
23:01:30.006 [pimatic-meross] Handled error getOnlineStatus: Error: Timeout
23:01:30.469 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 reconnected: undefined
Connected. Subscribe to user topics
23:01:30.614 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 connected
Closing mqtt: undefined
Connect to cloud error: null
23:01:40.870 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 reconnected: undefined
Connected. Subscribe to user topics
23:01:41.025 [pimatic-meross] DEV: 1912063268451725187748e1e912ddc2 connected

**Comment by Apollon77** [comment]
Honestly ... no idea ... Also no idea from where the logs "in betweek the ones with DEV" comes from. it seems that the connection gets closed. ALso with all those "undefined" and "Null" details seems missing.

We have one case with ioBroker (see https://github.com/Apollon77/ioBroker.meross/issues/111) where some devices seem to get a "Server unavailable" error and we still do not know why and why only some ... Seems to be the same but as said there seems to be a log issue with the pimatic log or such, and so it is only an assumption :-(

**Comment by bertreb** [comment]
In the ioBroker case seems like there's never a connection. I my case the connect is successful but after a few seconds the 'close' event happens and triggers the reconnect. One of my assumptions is that the mqtt connection is closed, but i can't get log info on that. 
The 'null' or 'undefined' is not existing error/close event info. 

Example (coffeescript)
```
@meross.on 'close', (deviceId, error) =>
    pimatic.logger deviceId + ' closed: ' + error
```
The resulting log:  '1912063268451725187748e1e912ddc2 closed: null'

**Comment by Apollon77** [comment]
The adapter uses the npm library MQTT. Maybe check their readme on how to get more debug? Maybe they use the debug lib and do a env variable could bring more logs

**Comment by bertreb** [comment]
Ok thanks. I will try

**Comment by bertreb** [comment]
Did some debugging. I found that changing the meross mqtt domain server solves the issue.
I changed in file index.js in meross-cloud
```
222        const domain = this.dev.domain || "eu-iot.meross.com";
to
222        const domain = this.dev.domain || "iot.meross.com";
```

**Comment by Apollon77** [comment]
And it works only with the other domain or with both?

**Comment by bertreb** [comment]
It works with both domains (with the reconnects).
To test it i changed line 14
```
const MEROSS_URL = 'https://iot.meross.com';
```
iot.meross.com or eu-iot.meross.com have same result

**Comment by bertreb** [comment]
This morning I did another debug attempt and discovered that the repeating connecting error was gone.
I didn't change anything, so i assume that on the Meross cloud side something changed / was fixed.
My question is answered :)

**Comment by Apollon77** [comment]
Also wi Tee h the Original Code and URLs?

**Comment by bertreb** [comment]
yes I reinstalled meross-cloud and mqtt to be sure.
It's always tricky to say its solved if you didn't found the problem but it seems the problem is gone.
