### ISSUE TITLE
MQTT Connection - constantly connects and closes

### ISSUE THREAD

**Issue by mjrinker** [Apollon77/meross-cloud#91]
I recently implemented this package on my Node server and set up the simple device listeners as per [example.js](https://github.com/Apollon77/meross-cloud/blob/master/example/example.js), and I've noticed that the devices are constantly connecting and closing, often within only a few seconds of each other.

I didn't think this was a big deal so I ignored it, but then I just got an email from Meross saying my cloud service has been terminated due to high message volume. They said they will resume my service pending me fixing my issues that are causing this high volume. I was previously using albertogeniola's Python API [here](https://github.com/albertogeniola/MerossIot), but I wanted a purely NodeJS solution so I went with this one (which I think is awesome and I love the use of listeners).

I'm not sure whether this issue is purely coincidental or if it's a bug in this project, but I was hoping you might be able to shed some light on why I might be seeing this issue and/or any possible solutions to it.

Thanks!

**Comment by Apollon77** [comment]
In fact a comparable isue was reported with some devices and a special firmware from them in https://github.com/Apollon77/ioBroker.meross/issues/111 ... because of thefcat that I do not have such an affected device I was not able to reproduce the issue to see whats different. In fact the python library was kind of the base for this version and they should do "the same "basically.

If you have acces to both and could add debug and try to figure out whats the difference then I'm happy to get more infos.

Unless this we need to wait till I get such a device and find the time to reproduce it (if it is the same reason in your case)

**Comment by mjrinker** [comment]
I read through that issue and it was instructive. My device is a MSL120B (Smart WiFi Bulb). Do you have one of those? I can send you one if you need. I will try to get debug info but I think I'll need to wait for Meross to reactivate my service first.

I found [this issue](https://github.com/knolleary/pubsubclient/issues/372) (which is not Meross-specific) which says that using the same client ID can cause this issue. It looks like the clientID is constructed by hashing the device UUID. I'm guessing this cannot be changed, or else Meross Cloud will not know which device to connect?

**Comment by Apollon77** [comment]
I also checked the python code again ... let me try a "short" fix. So if you got enabled again lease install from github

npm i Apollon77/meross-cloud

is that working?

**Comment by mjrinker** [comment]
You're awesome, thank you! I will test it when I get reenabled.
I also wondered if my issue could stem from the fact that I don't disconnect the clients when I terminate my app.
I have it set to logout of Meross when I send a SIGINT (CTRL + C) to the app, but not disconnect the clients.

**Comment by Apollon77** [comment]
I think it is just that some devices with newer firmware connect differently to the cloud themself maybe. SO I tried to adjust some stuff as it was changed in python lib so far

**Comment by mjrinker** [comment]
It looks like that did the trick! Thank you!

**Comment by Apollon77** [comment]
I still need to do a bigger restrucuring because it seems that one mqtt connection is sufficient (currently it does one per device) ... but need to find time for this

**Comment by mjrinker** [comment]
Hm, so when [this issue](https://github.com/knolleary/pubsubclient/issues/372) mentions needing a unique client ID, is it not per device?

**Comment by Apollon77** [comment]
also the php lib changed from using the device-uuid to a random uuid :-)
