### ISSUE TITLE
meross_cloud_1.MerossCloud is not a constructor

### ISSUE THREAD

**Issue by donavanbecker** [Apollon77/meross-cloud#93]
**Describe the bug**  
When trying to connect to meross could getting 

`meross_cloud_1.MerossCloud is not a constructor`

**To Reproduce**  
See [L80-L130](https://github.com/donavanbecker/homebridge-meross/blob/b26a573b4657f95357c9630aaf19ec0ae92171e6/src/platform.ts#L80-L130
)

**Expected behavior**  
Logging to Meross Cloud

**Screenshots & Logfiles**
```
TypeError: meross_cloud_1.MerossCloud is not a constructor
    at MerossPlatform.discoverDevices (/Users/donavanbecker/GitHub/homebridge-meross/src/platform.ts:87:20)
    at HomebridgeAPI.<anonymous> (/Users/donavanbecker/GitHub/homebridge-meross/src/platform.ts:47:12)
    at HomebridgeAPI.emit (node:events:329:20)
    at HomebridgeAPI.signalFinished (/Users/donavanbecker/GitHub/homebridge-meross/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/Users/donavanbecker/GitHub/homebridge-meross/node_modules/homebridge/src/server.ts:160:14)
    at cli (/Users/donavanbecker/GitHub/homebridge-meross/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/Users/donavanbecker/GitHub/homebridge-meross/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
```

**Versions:**
 - Node version: v15.2.1
 - Operating system: macOS Big Sur

**Additional context**  
Using with Homebridge, which shouldn't matter.

**Comment by Apollon77** [comment]
Easy ... your line

> import { DeviceDefinition, MerossCloud, MerossCloudDevice } from 'meross-cloud';

is wrong!

the meross-cloud package DO NOT exports a MerossCloud object, it IS the object, also the other two exports are not done.

No idea what you wrive it that way ... the example shows how it works (sure in normal JS and not TS) ...

Sorry, please correct your code

**Comment by donavanbecker** [comment]
@Apollon77 I corrected it and it's working now! Thanks

**Comment by Apollon77** [comment]
Great to hear. Have fun.

**Comment by donavanbecker** [comment]
@Apollon77 if you have any pointers on reading and writing to `Meross-cloud` on my [homebridge-plugin](https://github.com/donavanbecker/homebridge-meross-cloud/tree/beta) much would be appriciated.

**Comment by Apollon77** [comment]
what exactly you mean?
In fact the ioBroker.meross is implementing anything the linrary offers and made sense for end users :-) maybe you get an idea there?

**Comment by donavanbecker** [comment]
https://github.com/donavanbecker/homebridge-meross-cloud/blob/de462831fd4a8e10c1117132fd9d0412166d0bc3/src/Devices/mss620.ts#L117

https://github.com/donavanbecker/homebridge-meross-cloud/blob/de462831fd4a8e10c1117132fd9d0412166d0bc3/src/Devices/mss620.ts#L137

Just wondering what would be used to update the values? with Meross-cloud

**Comment by Apollon77** [comment]
I'm not sure if I get you ... updates come in automatically as soon as the connection gets opened. and yes for all controlling options there are methods ... controlToggle(boolean) as example. The second parameter is a callback function to be called after the cloud acknowledge the command - or an error on timeot. So provide a callback function there and NO string!!

Starting https://github.com/Apollon77/ioBroker.meross/blob/e30249c45d0aaa74200987d4be6194208495ecc4/main.js#L936 ou can see what I do in the ioBroker adapter to initialize anything. To get all initial values for anything I use https://github.com/Apollon77/ioBroker.meross/blob/e30249c45d0aaa74200987d4be6194208495ecc4/main.js#L950 ... then you have all details in one struct and can initialize anything and have current values ... all updates come in as messages afterwards
